services:
  chat-fmc-ai:
    profiles: ["no-proxy"]
    container_name: chat-fmc-ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8004:3000
    environment:
      # Elastic logging configuration
      - ENABLE_ELASTIC_LOG=$ENABLE_ELASTIC_LOG
      - ELASTIC_LOG_HOST=$ELASTIC_LOG_HOST
      - ELASTIC_LOG_INDEX=$ELASTIC_LOG_INDEX
      # Other environment variables
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_URL=$GOOGLE_URL
      - CODE=$CODE
      - ENABLE_MCP=$ENABLE_MCP
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - CUSTOM_MODELS=$CUSTOM_MODELS
      - DEFAULT_MODEL=$DEFAULT_MODEL
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - ANTHROPIC_API_VERSION=$ANTHROPIC_API_VERSION
      - ANTHROPIC_URL=$ANTHROPIC_URL
      - WHITE_WEBDAV_ENDPOINTS=$WHITE_WEBDAV_ENDPOINTS
      - SILICONFLOW_API_KEY=$SILICONFLOW_API_KEY
      - SILICONFLOW_URL=$SILICONFLOW_URL
      - DATABASE_URL=$DATABASE_URL
      - LOGTO_ENDPOINT=$LOGTO_ENDPOINT
      - LOGTO_APP_ID=$LOGTO_APP_ID
      - LOGTO_APP_SECRET=$LOGTO_APP_SECRET
      - LOGTO_BASE_URL_PROD=$LOGTO_BASE_URL_PROD
      - LOGTO_BASE_URL_DEV=$LOGTO_BASE_URL_DEV
      - LOGTO_COOKIE_SECRET=$LOGTO_COOKIE_SECRET
      - LOGTO_M2M_APP_ID=$LOGTO_M2M_APP_ID
      - LOGTO_M2M_APP_SECRET=$LOGTO_M2M_APP_SECRET

  chatgpt-next-web-proxy:
    profiles: ["proxy"]
    container_name: chatgpt-next-web-proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      # Elastic logging configuration
      - ENABLE_ELASTIC_LOG=$ENABLE_ELASTIC_LOG
      - ELASTIC_LOG_HOST=$ELASTIC_LOG_HOST
      - ELASTIC_LOG_INDEX=$ELASTIC_LOG_INDEX
      # Other environment variables
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - GOOGLE_URL=$GOOGLE_URL
      - CODE=$CODE
      - PROXY_URL=$PROXY_URL
      - ENABLE_MCP=$ENABLE_MCP
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRES_IN=$JWT_EXPIRES_IN
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - CUSTOM_MODELS=$CUSTOM_MODELS
      - DEFAULT_MODEL=$DEFAULT_MODEL
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - ANTHROPIC_API_VERSION=$ANTHROPIC_API_VERSION
      - ANTHROPIC_URL=$ANTHROPIC_URL
      - WHITE_WEBDAV_ENDPOINTS=$WHITE_WEBDAV_ENDPOINTS
      - SILICONFLOW_API_KEY=$SILICONFLOW_API_KEY
      - SILICONFLOW_URL=$SILICONFLOW_URL
      - DATABASE_URL=$DATABASE_URL
      - LOGTO_ENDPOINT=$LOGTO_ENDPOINT
      - LOGTO_APP_ID=$LOGTO_APP_ID
      - LOGTO_APP_SECRET=$LOGTO_APP_SECRET
      - LOGTO_BASE_URL_PROD=$LOGTO_BASE_URL_PROD
      - LOGTO_BASE_URL_DEV=$LOGTO_BASE_URL_DEV
      - LOGTO_COOKIE_SECRET=$LOGTO_COOKIE_SECRET
      - LOGTO_M2M_APP_ID=$LOGTO_M2M_APP_ID
      - LOGTO_M2M_APP_SECRET=$LOGTO_M2M_APP_SECRET
